CREATE DATABASE InstagramDB;

USE InstagramDB;


CREATE TABLE Users (
    UserID INT IDENTITY(1,1) PRIMARY KEY,
    Username NVARCHAR(50) NOT NULL UNIQUE,
    Email NVARCHAR(100) NOT NULL UNIQUE,
	ProfilePictore NVARCHAR(225) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255) NOT NULL,
    Bio NVARCHAR(255),
    JoinDate DATE NOT NULL
);


CREATE TABLE Posts (
    PostID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT FOREIGN KEY REFERENCES Users(UserID),
    Caption NVARCHAR(255),
    MediaType NVARCHAR(20) NOT NULL,
    PostDate DATETIME NOT NULL
);


CREATE TABLE Stories (
    StoryID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT FOREIGN KEY REFERENCES Users(UserID),
    Content NVARCHAR(255) NOT NULL,
    PostDate DATETIME NOT NULL,
    ExpiryDate DATETIME NOT NULL
);

CREATE TABLE Likes (
    LikeID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT FOREIGN KEY REFERENCES Users(UserID),
    PostID INT FOREIGN KEY REFERENCES Posts(PostID),
    LikeDate DATETIME NOT NULL
);


CREATE TABLE Comments (
    CommentID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT FOREIGN KEY REFERENCES Users(UserID),
    PostID INT FOREIGN KEY REFERENCES Posts(PostID),
    CommentText NVARCHAR(255) NOT NULL,
    CommentDate DATETIME NOT NULL
);

CREATE TABLE Follow (
    FollowerID INT NOT NULL,
    FollowedID INT NOT NULL,
    DateFollowed DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (FollowerID, FollowedID),
    FOREIGN KEY (FollowerID) REFERENCES Users(UserID),
    FOREIGN KEY (FollowedID) REFERENCES Users(UserID)
);



CREATE TABLE DirectMessage (
    MessageID INT IDENTITY(1,1) PRIMARY KEY,
    SenderID INT NOT NULL,
    ReceiverID INT NOT NULL,
    MessageText TEXT NOT NULL,
    DateSent DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SenderID) REFERENCES Users(UserID),
    FOREIGN KEY (ReceiverID) REFERENCES Users(UserID)
);